### ISSUE TITLE
Response.raw accessed without setting stream to True

### ISSUE THREAD

**Issue by skestle** [amnong/easywebdav#11]
Requests specifies that response's raw access requires streaming be turned on (https://github.com/kennethreitz/requests/blob/master/requests/models.py#L476).

Failing to do this breaks zipped downloads against requests 1.2.3 (but works on 1.1.0)

For more info, see the analysis over at requests: https://github.com/kennethreitz/requests/issues/1481

**Comment by victorgp** [comment]
Fixed in this pull request, let's see if the owner merges it

https://github.com/amnong/easywebdav/pull/13
