### ISSUE TITLE
shutil.copyfileobj(response.raw, f) doesn't work for me

### ISSUE THREAD

**Issue by mentaal** [amnong/easywebdav#16]
Hi there, 
Can I just start by saying that this is a very nice little module!
I am trying to download a file from a Sharepoint site and when I do so I end up with an empty file. 
I looked in the code and tried using your original (i'm guessing) line: f.write(response.content) @line 126 of client.py which works just fine for me instead of the shutil.copyfileobj method call.
I can't figure out what is wrong, your code looks fine. Could it be something up on my end?
I am in business anyway but I just thought I would point this out. 
Thanks!

**Comment by amnong** [comment]
Hey Mentaal,
Glad you're enjoying my library. Unfortunately I've been neglecting it for the past year and a half, sorry for that.

This really sounds like #9 and #11. You should beware - if this is indeed the case, you may have a serious memory problem when downloading large files.

I'm going to pull a pending merge request really soon, which should fix this problem.

Thanks,
Amnon

**Comment by amnong** [comment]
Closing for lack of response. Please reopen if you still encounter the problem.
