### ISSUE TITLE
Updates/Maintenance in pypi

### ISSUE THREAD

**Issue by KillerX** [amnong/easywebdav#17]
@amnong I unfortunately am unable to find a nice way of privately contacting you so I am raising this as an issue here.

Would you consider adding someone as a maintainer for this project on pypi, so new versions of this great package could be released. I believe it would be of big help to many python devs who have to deal with WebDav to be able to take full advantage of this library directly via pip, and not by having to manually cobble together a fork with all patches that they need.

If you would be willing to consider letting me become a maintainer of the package in pipy or have any questions feel free to drop an email to killerx (at) sess-on.net

**Comment by kartoch** [comment]
+1, I've just merging lot of previous pull requests and alone branches. Is there any policy on pypy about unmaintened projects ?

**Comment by pfalcon** [comment]
Guys, just stating the obvious, if the author won't respond in some reasonable time, you can fork a project and upload it under new name (say, easywebdav2) on PyPI, and hope for reintegration at later time. Of course, that's not something to pull the trigger with, so your attempts to contact the author are appreciated (by module users, and hopefully by the author himself).

**Comment by amnong** [comment]
Hello everyone. I apologize for being unavailable for so long. I'll review all requests soon if I have the time, otherwise I'll grant some of you collaboration privileges.

I really do appreciate your contributions. I imagine how frustrating my lack of response has been, and again, my sincere apologies.

Thanks,
Amnon

**Comment by kartoch** [comment]
thanks for your reply and works @amnong.

**Comment by amnong** [comment]
Hello again everyone,
I've updated the project, added system tests and uploaded v1.1.0 to PyPI. Do any of you have any open issues currently? If so, please report them. Also, if you wish to merge your forks into this project please let me know.

**Comment by KillerX** [comment]
Thanks for the responses and for the continued work!
