### ISSUE TITLE
ls command does not work

### ISSUE THREAD

**Issue by kartoch** [amnong/easywebdav#19]
I'm trying to ls a directory with latest version, but I have the following error message:

```
File "/home/kartoch/opt/python/pelican/src/easywebdav/easywebdav/client.py", line 174, in ls
  tree = xml.parse(StringIO(response.content))
TypeError: initial_value must be str or None, not bytes
```

**Comment by amnong** [comment]
Yes... I committed this late last night and then I noticed there might be a
bug there, and also I need to test again with Python 3. Anyway the use of
io.BytesIO is wrong, and so is the use of response.content....
