### ISSUE TITLE
upload() may lead to uncontrolled memory usage

### ISSUE THREAD

**Issue by pfalcon** [amnong/easywebdav#2]
upload() tries to load entire file into memory, and thus will cause trouble with more or less big files. This should be fixed by using buffer chunks, like download() already does.

**Comment by pfalcon** [comment]
It seems that neither requests nor urllib2 support efficient handling of POST/PUT data. Funky.

**Comment by pfalcon** [comment]
Ah, ok, it all reduces to http://docs.python.org/library/httplib.html#httplib.HTTPConnection.request which supports the needed thing in a natural way.

**Comment by amnong** [comment]
Hey there,
Just wanted to let you know I'm currently abroad on vacation, but I'm going to address this issue and the others when I get back home in early October. If this is urgent for you, please feel free to implement stuff and send me patches or pull/merge requests or whatever. If you don't wanna implement stuff on your own that's fine, and again, I'll address the issues when I'm back home. Thanks :)

**Comment by pfalcon** [comment]
Thanks for quick response! I just spent an evening to refresh me on the state of python webdav libs, and really liked easywebdav, so decided to file any issues I saw with it. It may take me some time before I get to actually using it in a project, but if I do that earlier than you, I definitely will submit any patches.

**Comment by amnong** [comment]
Hey @pfalcon,
It's been so long, sorry for delaying this problem... Did you eventually reach any conclusions regarding this issue?

**Comment by pfalcon** [comment]
Unfortunately, I didn't have chance to work on webdav stuff like I planned, so I couldn't look into this issue. If you think that its staying open is not productive, feel free to close it.

**Comment by amnong** [comment]
I just looked at the code again, and clearly there was a problem. I fixed it just now in v1.2.0.
