### ISSUE TITLE
Directory listing support

### ISSUE THREAD

**Issue by pfalcon** [amnong/easywebdav#3]
> Note: Directory listing is not supported. I'll implement it upon request.

Here's the request ;-). The library is a fresh breath from the bloat/mess present in other py libraries, but without ls(), it's hard to just start playing with it.

**Comment by 2xyo** [comment]
+1

**Comment by amnong** [comment]
Hey guys, this has already been implemented. See this pull request: https://github.com/amnong/easywebdav/pull/4

Closing this issue for now, please feel free to reopen it if the current implementation does not answer the requirement.

Thanks!
