### ISSUE TITLE
Implement move and copy methods

### ISSUE THREAD

**Issue by travcunn** [amnong/easywebdav#40]

**Comment by luckydonald** [comment]
Here is a reference:
[Mdsn](https://msdn.microsoft.com/en-us/library/ms879464%28v=exchg.65%29.aspx)
Rename is just a move with same destination path.

**Comment by travcunn** [comment]
I see! Thanks for pointing that out to me.

**Comment by luckydonald** [comment]
Is this implemented?

**Comment by luckydonald** [comment]
It seems to be implemeted but is not yet merged: https://github.com/amnong/easywebdav/pull/33
